import { z } from 'zod';

// UUIDs are generated by Prisma's @default(uuid()). Validating the shape here
// keeps malformed ids out of Azure AI Search OData filters and DB queries.
const uuid = z.string().uuid('Must be a valid document id');

export const registerSchema = z.object({
  body: z.object({
    email: z.string().trim().toLowerCase().email('Invalid email address'),
    password: z
      .string()
      .min(8, 'Password must be at least 8 characters')
      .max(200, 'Password is too long'),
    // Optional to match the UI, which allows sign-up without a display name.
    name: z.string().trim().min(2, 'Name must be at least 2 characters').max(100).optional(),
  }),
});

export const loginSchema = z.object({
  body: z.object({
    email: z.string().trim().toLowerCase().email('Invalid email address'),
    password: z.string().min(1, 'Password is required'),
  }),
});

export const documentIdParamSchema = z.object({
  params: z.object({
    documentId: uuid,
  }),
});

export const chatSchema = z.object({
  params: z.object({
    documentId: uuid,
  }),
  body: z.object({
    message: z.string().trim().min(1, 'Message cannot be empty').max(2000, 'Message is too long'),
  }),
});

export const searchSchema = z.object({
  query: z.object({
    q: z.string().trim().min(1, 'Search query cannot be empty').max(400, 'Search query too long'),
    top: z.coerce.number().int().min(1).max(50).optional(),
  }),
});

export const listDocumentsSchema = z.object({
  query: z.object({
    page: z.coerce.number().int().min(1).optional(),
    limit: z.coerce.number().int().min(1).max(100).optional(),
  }),
});
